require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Glokool' do
  config = use_native_modules!

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  
  use_react_native!(:path => config["reactNativePath"])
  pod 'Firebase/Analytics'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'RNPaypal', :path => '../node_modules/react-native-paypal'


  pod 'IamportReactNative', :path => '../node_modules/iamport-react-native'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'GlokoolTests' do
    inherit! :complete
    # Pods for testing
  end

 # Enables Flipper.
 #
 # Note that if you have use_frameworks! enabled, Flipper will not work and
 # you should disable the next line.
 # use_flipper!({ 'Flipper' => '0.74.0' })
 # post_install do |installer|
 # flipper_post_install(installer)
 # end
end

target 'Glokool-tvOS' do
  # Pods for Glokool-tvOS

  target 'Glokool-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
